{% set name = 'gridtk' %}
{% set project_dir = environ.get('RECIPE_DIR') + '/..' %}

package:
  name: {{ name }}
  version: {{ environ.get('BOB_PACKAGE_VERSION', '0.0.1') }}

build:
  number: {{ environ.get('BOB_BUILD_NUMBER', 0) }}
  run_exports:
    - {{ pin_subpackage(name) }}
  script:
    - cd {{ project_dir }}
    {% if environ.get('BUILD_EGG') %}
    - python setup.py sdist --formats=zip
    {% endif %}
    - python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python {{ python }}
    - setuptools {{ setuptools }}
    - bob.extension
  run:
    - python
    - drmaa

test:
  imports:
    - {{ name }}
  commands:
    - bob jman --help
  requires:
    - bob-devel {{ bob_devel }}.*
    - nose
    - coverage
    - sphinx
    - sphinx_rtd_theme

about:
  home: https://www.idiap.ch/software/bob/
  summary: HPC Job Manager
  license: BSD 3-Clause
  license_family: BSD
